#
# Generated by the Apple Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = WordNet

PROJECTVERSION = 2.8
PROJECT_TYPE = Application
NEXTSTEP_APPICON = WordNet.tiff
ICONSECTIONS =	-sectcreate __ICON app WordNet.tiff

English_RESOURCES = SearchWindow.nib WordNet.nib License.nib\
                    WordNet-windows.nib Preferences.nib Credits.rtf

LANGUAGES = English

GLOBAL_RESOURCES = WordNet.tiff FactoryDefaults.plist

CLASSES = EDApplication.m WNAppController.m WNSearchWindowController.m\
          WNPrefPanelController.m WNTextView.m

HFILES = EDApplication.h Constants.h WNAppController.h\
         WNSearchWindowController.h WNPrefPanelController.h WNTextView.h

MFILES = WordNet_main.m Constants.m

SUBPROJECTS = WordNetAccess.subproj

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble m.template\
            h.template java.template CustomInfo.plist


MAKEFILEDIR = $(MAKEFILEPATH)/pb_makefiles
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = app.make
NEXTSTEP_INSTALLDIR = $(HOME)/Applications
WINDOWS_INSTALLDIR = /MyApps
LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


NEXTSTEP_PB_CFLAGS = -DUNIX -Dunix -DWORDNET_OSXSBUILD
FRAMEWORKS = -framework Foundation -framework AppKit\
             -framework EOControl


NEXTSTEP_OBJCPLUS_COMPILER = /usr/bin/cc
WINDOWS_OBJCPLUS_COMPILER = $(DEVDIR)/gcc
PDO_UNIX_OBJCPLUS_COMPILER = $(NEXTDEV_BIN)/gcc
NEXTSTEP_JAVA_COMPILER = /usr/bin/javac
WINDOWS_JAVA_COMPILER = $(JDKBINDIR)/javac.exe
PDO_UNIX_JAVA_COMPILER = $(NEXTDEV_BIN)/javac

include $(MAKEFILEDIR)/platform.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
